version: '3.8'

services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work  # Директория для хранения ваших ноутбуков
    environment:
      - JUPYTER_ENABLE_LAB=yes  # Включаем JupyterLab
    restart: unless-stopped